#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_terrainer = env_modules.Clone()

env_terrainer.Append(CPPDEFINES=["TERRAINER_MODULE"])

env_terrainer.add_source_files(env.modules_sources, "*.cpp")
# if env.editor_build:
#     env_terrain.add_source_files(env.modules_sources, "editor/*.cpp")
